name: Discord Notification

on:
  workflow_run:
    workflows: ["Continuous Delivery"]
    types:
      - completed

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord
        run: |
          STATUS="${{ github.event.workflow_run.conclusion }}"
          REPO="${{ github.repository }}"
          ACTOR="${{ github.actor }}"
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"

          if [ "$STATUS" = "success" ]; then
            MSG="✅ CD finalizado com sucesso!\n📦 Repo: $REPO\n👤 Autor: $ACTOR\n🔗 $RUN_URL"
          else
            MSG="❌ CD falhou!\n📦 Repo: $REPO\n👤 Autor: $ACTOR\n🔗 $RUN_URL"
          fi

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"$MSG\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}